version: '3'

vars:
  IMAGE_NAME: cz-natours-app
  REGISTRY: r.hansdog.dev

tasks:
  run:
    desc: 'start the dev server'
    cmds:
      - nodemon server.js
  run:prod:
    desc: 'start the prod server'
    cmds:
      - NODE_ENV=production nodemon server.js

  image:
    desc: 'Build the Docker image'
    preconditions:
      - sh: docker version
    cmds:
      - docker build -t {{.IMAGE_NAME}} .

  push:
    desc: 'Push the Docker image to the registry'
    preconditions:
      - sh: docker version
    cmds:
      - docker tag {{.IMAGE_NAME}} {{.REGISTRY}}/{{.IMAGE_NAME}}:latest
      - docker push {{.REGISTRY}}/{{.IMAGE_NAME}}:latest

  imagerun:
    desc: 'run docker container from local to image'
    preconditions:
      - sh: docker version
    cmds:
      - docker run --rm --name {{.IMAGE_NAME}} -p 3000:3000 {{.IMAGE_NAME}}

  deploy:
    desc: Build image, push and deploy to NAS2
    cmds:
      - task: image
      - task: push
      - 'curl -H "Authorization: Bearer lbuHehLxXpWdmpWhEoX4" 10.0.0.4:5050/v1/update'

  debug:
    desc: 'Debug local'
    cmds:
      - ndb server.js
